cask_args appdir: '/Applications'

tap 'caskroom/cask'
tap 'homebrew/bundle'

brew 'ansible'
brew 'awscli'
brew 'coreutils'
brew 'curl'
brew 'ffmpeg'
brew 'gnupg'
brew 'go'
brew 'grc'
brew 'httpie'
brew 'irssi'
brew 'jp2a'
brew 'jq'
brew 'libcaca', args: ['with-imlib2']
brew 'libgit2'
brew 'nmap'
brew 'node'
brew 'openssl'
brew 'readline'
brew 'python3'
brew 'readline'
brew 'ruby-build'
brew 'rbenv'
brew 'roundup'
brew 's3cmd'
brew 'tmux'
brew 'unrar'
brew 'wget'
brew 'youtube-dl'

cask 'adium'
cask 'atom'
cask 'firefox'
cask 'google-chrome'
cask 'handbrake'
cask 'slack'
cask 'vlc'
