cask_args appdir: '/Applications'

tap 'caskroom/cask'
tap 'homebrew/bundle'

brew 'ansible'
brew 'autossh'
brew 'awscli'
brew 'bash'
brew 'coreutils'
brew 'curl'
brew 'git'
brew 'git-crypt'
brew 'git-extras'
brew 'gnu-sed'
brew 'gnupg'
brew 'gnutls'
brew 'go'
brew 'grc'
brew 'groovy'
brew 'hping'
brew 'httrack'
brew 'jp2a'
brew 'jq'
brew 'kops'
brew 'kubernetes-helm'
brew 'libcaca', args: ['with-imlib2']
brew 'libgcrypt'
brew 'libgit2'
brew 'libpng'
brew 'libxml2'
brew 'micro'
brew 'ncdu'
brew 'ngrep'
brew 'nmap'
brew 'openssl'
brew 'rbenv'
brew 'readline'
brew 'packer'
brew 'pyenv'
brew 'rbenv'
brew 'readline'
brew 'ruby-build'
brew 's3cmd'
brew 'shellcheck'
brew 'terminal-notifier'
brew 'terragrunt', force: true, conflicts_with: ['tfenv']
brew 'tfenv'
brew 'tmux'
brew 'tree'
brew 'unrar'
brew 'wget'

cask 'atom'
cask 'chefdk'
cask 'firefox'
cask 'google-chrome'
cask 'iterm2'
cask 'java'
cask 'minikube'
cask 'slack'
cask 'sublime-text'
cask 'tunnelblick'
cask 'vagrant'
cask 'virtualbox'
cask 'xquartz'
